apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: plog-backend-role

rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]