apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plog-backend-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]