apiVersion: v1
kind: PersistentVolume
metadata:
  name: k6-script-pv
  namespace: plog # 명시하였지만 pv는 cluster 공용
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k6-scripts"
  storageClassName: k6-script