version: '3.8'

networks:
  metric-bridge-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:

services:
  spring-mock-service:
    container_name: spring-mock-service
    image: spring-mock-service:latest
    ports:
      - "8080:8080"
    networks:
      - metric-bridge-network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - metric-bridge-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
    networks:
      - metric-bridge-network
    depends_on:
      - influxdb

  k6-test-runner:
    image: grafana/k6
    container_name: k6-test-runner
    ports:
      - "5665:5665"
    networks:
      - metric-bridge-network
    volumes:
      - ./k6/scripts:/scripts
    entrypoint: ["sleep"]
    command: ["infinity"]
    depends_on:
      - spring-mock-service
      - influxdb
