apiVersion: v1
kind: Service

metadata:
  name: k6-runner-service

spec:
  type: NodePort
  selector:
    app: k6-runner
  ports:
    - name: k6-api-port
      port: 3000
      nodePort: 31000
      targetPort: 3000
      protocol: TCP