apiVersion: v1
kind: Service
metadata:
  name: k6-dashboard-svc
spec:
  type: NodePort
  selector:
    app: k6-runner
  ports:
    - protocol: TCP
      port: 5665
      targetPort: 5665
      nodePort: 30065
