apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-chart-pv
  namespace: plog # 명시하였지만 pv는 cluster 공용
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/helm-chart"
  storageClassName: helm-chart