apiVersion: v1
kind: PersistentVolume
metadata:
  name: k6-script-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/k6-scripts
  storageClassName: k6-script