apiVersion: v1
kind: Service

metadata:
  name: spring-mock-service
  namespace: test

spec:
  type: NodePort
  selector:
    app: spring-mock

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
