apiVersion: apps/v1
kind: Deployment
metadata:
  name: semi-medeasy-redis-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semi-medeasy-redis
  template:
    metadata:
      labels:
        app: semi-medeasy-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"

          command: ["sh", "-c"]
          args:
            - "redis-server --requirepass $REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis_password
                  name: semi-medeasy-redis-secret