apiVersion: v1
kind: Service
metadata:
  name: semi-medeasy-redis-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379          # 클러스터 내부에서 접근할 포트
      targetPort: 6379    # 컨테이너 포트
      nodePort: 30379     # 노드 외부에서 접근할 포트 (30000~32767 범위)
