# charts/plog-apps/templates/secrets.yaml
{{- range $appName, $appConfig := .Values.applications }}
  {{- if and $appConfig.enabled $appConfig.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $appName }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
type: Opaque
data:
  {{- range $key, $value := $appConfig.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- end }}