apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-daemonset
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: telegraf
          image: telegraf:1.30
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
