apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-mock-deployment
  namespace: test

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mock

  template:
    metadata:
      labels:
        app: spring-mock
    spec:
      containers:
        - name: spring-mock-container
          imagePullPolicy: Always
          image: asia-northeast3-docker.pkg.dev/citric-replica-450012-a8/plog-image-repo/spring-mock-service:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcp-artifact-registry-secret

