apiVersion: v1
kind: PersistentVolume
metadata:
  name: semi-medeasy-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data
  storageClassName: semi-medeasy-db