apiVersion: v1
kind: Secret

metadata:
  name: plog-backend-secret
  namespace: plog

type: Opaque

stringData:
  k6_script_file_folder: "C:\\mnt\\k6-scripts"
  influxdb_host: "influxdb"
  influxdb_port: "8086"
  influxdb_database: "k6"

